### ISSUE TITLE
Allow the Build to Pass Even if Semver is Violated

### ISSUE THREAD

**Issue by RobbieMcKinstry** [obi1kenobi/cargo-semver-checks-action#10]
Many crates in the Rust ecosystem are pre-v1.0, and do not have Semver compatibility guarantees. This Action is still useful for maintainers who want _to know_ if a PR is breaking semver compliance, even if they want to merge the pull request anyway. 

For comparison, check out [Covcode's](https://github.com/codecov/codecov-action#arguments) `fail_ci_if_error` input. This Action input allows the status code of the Action to be set to 0 even if the Action itself fails.

**Comment by epage** [comment]
> Many crates in the Rust ecosystem are pre-v1.0, and do not have Semver compatibility guarantees.

They should be following cargo's variant of semver guarantees.

If you mean to not block a PR if it breaks a change because the crate is willing to bump to a breaking version, I proposed https://github.com/obi1kenobi/cargo-semver-checks-action/issues/1 as an alternative approach to blocking CI

**Comment by RobbieMcKinstry** [comment]
Today I learned about `continue-on-error`.

 https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
