### ISSUE TITLE
Allow enabling verbose output

### ISSUE THREAD

**Issue by rtzoeller** [obi1kenobi/cargo-semver-checks-action#16]
To provide increased insight into which checks were run even when successful, I would like to enable verbose output. It does not seem like the action provides a way to do that presently.

**Comment by obi1kenobi** [comment]
Good idea! I'm currently a bit swamped with a few time-sensitive items in `cargo-semver-checks` (and the new rustdoc version is causing a bit of headache as well).

I'm happy to add this when I get a few minutes to do it, and I'd also be happy to merge a PR that adds a `verbose` option and supplies the `-v` flag if set. If you might be interested in putting a PR together, I'd be happy to assist.
