### ISSUE TITLE
Add `manifest-path` option to specify the path to the Cargo.toml to check

### ISSUE THREAD

**Issue by ia0** [obi1kenobi/cargo-semver-checks-action#18]
Hi,

As far as I can tell, the action currently assumes there's a `Cargo.toml` at the root of the repository (either a crate or a workspace).

Could it be possible to specify the directory containing the `Cargo.toml`? (the default would be `.` i.e. the root of the repository)

Thanks!

**Comment by ia0** [comment]
I believe this could simply be implemented with `export CARGO_MANIFEST_DIR="${{ inputs.manifest-dir }}"`.

Note that there's currently no workaround. In similar cases I used to create a temporary `Cargo.toml` at the root before calling the action. But because the script does some `git checkout`, this doesn't work.

**Comment by obi1kenobi** [comment]
Good idea, thanks for suggesting it!

Out of curiosity, any particular reason to set the manifest _directory_ rather than the path to the manifest itself? I'm asking because the `cargo-semver-checks` binary itself takes `--manifest-path`. It would be simpler and easier to make the action match that behavior, since I'm planning for a "v2" version of the action that uses the binary more directly and doesn't rely as much on shell scripting.

**Comment by ia0** [comment]
No reason to prefer `CARGO_MANIFEST_DIR` over `--manifest-path`. I'm actually more used to `--manifest-path` because I don't like global state. So I would also prefer that but don't mind either way.

I just suggested `CARGO_MANIFEST_DIR` because I was trying to change the behavior from outside the action. But we can't set environment variables for actions apparently (there's a notion of environment variable but the action has to explicitly read it with `${{ env.foobar }}`).

**Comment by obi1kenobi** [comment]
Makes sense, thanks! I'll make sure a `manifest-path` option is available in the v2 action.

I'm currently on a family vacation and trying to limit how much time I spend on my laptop vs with my family, so the v2 action probably won't be ready for several more weeks. But I wouldn't like to block your work if I can avoid it, so if you'd like to add a `manifest-path` option to the current action, it should be quite a straightforward PR and I'd be happy to merge it.

**Comment by ia0** [comment]
No worries :-) I'll take a look if I have time. It's not urgent. Enjoy the time with your family!
