### ISSUE TITLE
Generates warning about set-output command being deprecated

### ISSUE THREAD

**Issue by scouten-adobe** [obi1kenobi/cargo-semver-checks-action#22]
## What happened

I used this action in a [recent workflow](https://github.com/adobe/xmp-toolkit-rs/actions/runs/4059340920/jobs/6987278306) and it generated a warning:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## What you expected to happen

No such warning

## How to reproduce it

Run any GitHub Actions workflow containing this action.

**Comment by obi1kenobi** [comment]
Thanks! Right now, these warnings are generated by upstream actions that don't appear to have been updated yet.

I'm hopeful that once #21 merges, most if not all of them will disappear. We'll re-evaluate this after that PR merges.

**Comment by mgr0dzicki** [comment]
And indeed there are no warnings since #21.

**Comment by obi1kenobi** [comment]
@scouten-adobe we'll be releasing v2 of this action shortly, and upgrading to that version will resolve this problem! Thanks for bearing with us while we worked through this!
