### ISSUE TITLE
Action v2 should version the cache based on cargo-semver-checks and Rust toolchain versions

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks-action#27]
Just leaving a note to remind us that the action's caching behavior should version based on the Rust toolchain version, and *not* the rustdoc format version: new Rust versions can ship bugfixes in rustdoc JSON that don't require a format change.

The cache should also be versioned by the `cargo-semver-checks` version, too.

Related: https://github.com/obi1kenobi/cargo-semver-checks/issues/415#issuecomment-1480266112

**Comment by mgr0dzicki** [comment]
@obi1kenobi, I believe this is realized now and might be closed, am I right?
