### ISSUE TITLE
Is it possible to make the `v` in version tags optional

### ISSUE THREAD

**Issue by najamelan** [obi1kenobi/cargo-semver-checks-action#4]
Currently the github action fails with this because I use version tags without the `v`. My tags are like `0.5.1`.
 ```
Comparison version: 0.5.1
+ export COMPARISON_TAG=v0.5.1
+ COMPARISON_TAG=v0.5.1
+ git fetch --depth=1 origin +refs/tags/v0.5.1:refs/tags/v0.5.1
fatal: couldn't find remote ref refs/tags/v0.5.1
Error: Process completed with exit code 128.
```

**Comment by obi1kenobi** [comment]
It should be possible already by setting the `version-tag-prefix` to the empty string like so:
```
- name: Check semver
  uses: obi1kenobi/cargo-semver-checks-action@v1
  with:
    version-tag-prefix: ''
```

I agree that this is not super clear in the README. I'll try to reorganize it a bit and make it easier to find.

**Comment by najamelan** [comment]
Thank you so much, this is awesome!
