### ISSUE TITLE
Typo in README: "feature" option should be "features"

### ISSUE THREAD

**Issue by HadrienG2** [obi1kenobi/cargo-semver-checks-action#56]
...or at least that's what the error message I get when I try to use the action with a "feature" option suggests ;)

> Warning: Unexpected input(s) 'feature', valid inputs are ['package', 'exclude', 'manifest-path', 'feature-group', 'features', 'verbose', 'release-type', 'rust-toolchain', 'shared-key', 'prefix-key', 'github-token']

**Comment by obi1kenobi** [comment]
Good catch, thanks! Fixed in #57 which should merge shortly.
