### ISSUE TITLE
Should update to node20 due to node16 deprecation

### ISSUE THREAD

**Issue by HadrienG2** [obi1kenobi/cargo-semver-checks-action#62]
Just noticed this in one of my CI jobs:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: obi1kenobi/cargo-semver-checks-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by obi1kenobi** [comment]
Thanks! Just opened a PR to fix this.
