### ISSUE TITLE
Allow opting into using sparse registry functionality

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks-action#7]
Requested:
https://www.reddit.com/r/rust/comments/x10f5u/comment/imbrage/?context=3

Perhaps as simple as adding `CARGO_UNSTABLE_SPARSE_REGISTRY=true` to the action.
https://internals.rust-lang.org/t/call-for-testing-cargo-sparse-registry/16862

**Comment by mgr0dzicki** [comment]
Implemented in #36.
