### ISSUE TITLE
Use pre-built binaries to make action faster

### ISSUE THREAD

**Issue by scouten-adobe** [obi1kenobi/cargo-semver-checks-action#8]
This action is our slowest PR validation check. I routinely see this action take ~2 minutes to build cargo-semver-checks from scratch on each PR validation run.

Please consider releasing binaries as part of your crate release process and downloading those boundaries in this GitHub action.

I refer you to https://github.com/aig787/cargo-udeps-action, which does this and is on-task in just a few seconds.

(Yes, I recognize the building-docs steps are going to be slow regardless.)

**Comment by obi1kenobi** [comment]
Thanks for opening this issue. The ~2min repeatedly spent compiling is definitely not good — I also just noticed it today and opened https://github.com/obi1kenobi/cargo-semver-check/issues/112 for the same purpose.

If you don't mind my curiosity, are you using `cargo-semver-checks` in private repos? I've been trying to figure out which targets we need binaries for, so I tried to find repos related to your account that use `cargo-semver-checks` to look that up, but every search came up blank.

**Comment by scouten-adobe** [comment]
@obi1kenobi thanks for following up on this. I don't have any private repos where this is in use (maybe someday?), but I am about to incorporate this into an open-source repo here: https://github.com/contentauth/c2pa-rs/pull/124/files

**Comment by scouten-adobe** [comment]
So, for now, I only care about `ubuntu-latest`.
