### ISSUE TITLE
Package registry login

### ISSUE THREAD

**Issue by memark** [obi1kenobi/cargo-semver-checks-action#88]
I'd like to add some more info to the CONTRIBUTING.md file regarding how to login to the github npm registry, where the @action-rs packages are located. I've tried a few different solutions
- adding GITHUB_TOKEN to .npmrc (but not committing it)
- using npm-cli-login
- using npm login

None of which feels fantastic... What is your preferred local workflow?

**Comment by obi1kenobi** [comment]
I'm very far from an expert here, so I just used `npm login` but if there's a better way, I'm open to it.
